"initial_thickness" = 0.025
"initial_radius" = 0.95
"initial_num_points" = 200
"initial_temperature" = 10.0
"compression_factor" = 1.1
"softness_factor" = 1.0
"how_smooth" = 8
"node_addition_threshold" = 0.025
"node_deletion_threshold" = 0.02
"low_high" = [-0.23, 0.23]
"recorders" = ["energy", "inner area", "num inner points", "num outer points", "outer perimeter"]
"temperature_param" = -0.05
"output_file_path" = "output.csv"
# o ------------ 0.41 ----------- o
# o ---- 0.205 -- o ---- 0.205 ---o
