"initial_thickness" = 0.05
"initial_radius" = 1.0
"initial_num_points" = 250
"initial_temperature" = 10.0
"compression_factor" = 1.1
"softness_factor" = 1.0
"how_smooth" = 8
"max_merge_steps_away" = 3 
"node_addition_threshold" = 0.010
"node_deletion_threshold" = 0.002 
"low_high" = [-0.2, 0.2]
"recorders" = ["K","log outer perimeter","log thickness","log convex perimeter"]
"temperature_param" = -0.05
"output_file_path" = "output_file01.csv"

"alpha" = 1.25

# o ------------ 0.41 ----------- o
# o ---- 0.205 -- o ---- 0.205 ---o
