"initial_thickness" = 0.025
"initial_radius" = 1.0
"initial_num_points" = 300
"initial_temperature" = 0.0
"compression_factor" = 1.1
"softness_factor" = 1.0
"how_smooth" = 10
"node_addition_threshold" = 0.05
"low_high" = [-0.2, 0.2]
